### ISSUE TITLE
Tutorial pipeline fails at update-deployment step

### ISSUE THREAD

**Issue by alif-munim** [openshift/pipelines-tutorial#105]
### Details
There isn't much info in the logs, but below is all I was able to find when looking through the `pipelinerun` yaml.
```
build-and-deploy-run-kw27h-update-deployment-2nnxc:
      pipelineTaskName: update-deployment
      status:
        conditions:
          - lastTransitionTime: '2020-10-02T18:53:52Z'
            message: >-
              bound workspaces did not match declared workspaces: provided extra
              values: [source]
            reason: TaskRunValidationFailed
            status: 'False'
            type: Succeeded
        podName: ''
        startTime: '2020-10-02T18:53:52Z'
```
I followed the pipelines tutorial on the [openshift docs](https://docs.openshift.com/container-platform/4.5/pipelines/creating-applications-with-cicd-pipelines.html) exactly, but I'm still running into this error.

Below is the command I'm running to start the `pipelinerun`, as written in the docs:
`tkn pipeline start build-and-deploy -w name=shared-workspace,claimName=source-pvc -p deployment-name=vote-api -p git-url=http://github.com/openshift-pipelines/vote-api.git -p IMAGE=image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/vote-api`

Any help would be appreciated. Thanks!
