### ISSUE TITLE
openshift-client (kind:Task) creation failed

### ISSUE THREAD

**Issue by rutvik23** [openshift/pipelines-tutorial#21]
While creating an openshift-client task, it failed with the message:
~~~
[core@master-0 ~]$ curl -O https://raw.githubusercontent.com/tektoncd/catalog/master/openshift-client/openshift-client-task.yaml
[core@master-0 ~]$ oc create -f openshift-client-task.yaml 
Error from server (InternalError): error when creating "openshift-client-task.yaml": Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: cannot unmarshal array into Go struct field ParamSpec.default of type string
~~~
However, I was able to create the s2i-java-8-task in the same way.

Version: OpenShift v4.1.14

**Comment by danielhelfand** [comment]
@rutvik23 There was an update to the `openshift-client` task that can be seen [here](https://github.com/tektoncd/catalog/pull/74). Unfortunately, how to properly version tasks hasn't been fully worked out yet. The task update requires the OpenShift Pipelines 0.6 operator, which has not been released yet.

To address this issue in the meantime, you can create the task how it was previously: 

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: openshift-client
spec:
  inputs:
    params:
      - name: ARGS
        description: The OpenShift CLI arguments to run
        default: help
  steps:
    - name: oc
      image: quay.io/openshiftlabs/openshift-cli-tekton-workshop:2.0
      command: ["/usr/local/bin/oc"]
      args:
        - "${inputs.params.ARGS}"
```

I also pulled a previous version of the image used for the task and pushed it to this Quay repo: `image: quay.io/openshiftlabs/openshift-cli-tekton-workshop:2.0`. I am not sure if there is a tag under the OpenShift Pipelines Quay that works with the task. But you will need to switch out the image as well for the task.

I opened an issue around versioning the task [here](https://github.com/tektoncd/catalog/issues/78).
