### ISSUE TITLE
PipelineRun Fails After Following Steps Under Trigger Pipeline

### ISSUE THREAD

**Issue by danielhelfand** [openshift/pipelines-tutorial#6]
After running the steps in this tutorial using an RHPDS 4.1 cluster, I triggered a pipeline after creating the git and image `PipelineResources` by running `oc create -f petclinic-deploy-pipelinerun.yaml` with the following:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: petclinic-deploy-pipelinerun-
spec:
  pipelineRef:
    name: deploy-pipeline
  trigger:
    type: manual
  serviceAccount: 'pipeline'
  resources:
  - name: app-git
    resourceRef:
      name: petclinic-git
  - name: app-image
    resourceRef:
      name: petclinic-image
```

After running `tkn pr ls` I get:
```
NAME                                 STARTED          DURATION   STATUS   
petclinic-deploy-pipelinerun-4pqkp   15 minutes ago   1 second   Failed  
```

I then looked through the events on my cluster and found the following error message:

```
Missing or invalid Task pipelines-tutorial/s2i-java-8: pods
        "petclinic-deploy-pipelinerun-qwq6k-build-hnq2g-pod-f9e7df" is
        forbidden: [minimum memory usage per Container is 6Mi, but request is
        0., minimum memory usage per Container is 6Mi, but request is 0.,
        minimum memory usage per Container is 6Mi, but request is 0., minimum
        memory usage per Container is 6Mi, but request is 0., minimum memory
        usage per Container is 6Mi, but request is 0., minimum memory usage per
        Container is 6Mi, but request is 0., minimum memory usage per Container
        is 6Mi, but request is 0.]
```

Running `tkn task ls -n pipelines-tutorial` shows that `s2i-java-8` was added:

```
NAME               AGE
openshift-client   1 hour ago
s2i-java-8         1 hour ago
```
