### ISSUE TITLE
Unable to trigger pipeline successfully

### ISSUE THREAD

**Issue by lungss** [openshift/pipelines-tutorial#63]
After issuing the command:
`$ tkn pipeline start build-and-deploy`

I'm seeing this in the log:
```
[build-ui : build] error building at STEP "LABEL "io.openshift.s2i.build.image" "registry.access.redhat.com/rhscl/python-36-rhel7" "io.openshift.s2i.build.source-location" "."": error ensuring container path "/opt/app-root/src": lstat /var/lib/containers/storage/overlay/5e00638bac323dbd1b4584674a5c9047b7ca6a32d63f84a75d4e72cd96e43827/merged/opt: invalid argument

failed to get logs for task build-ui : container step-build has failed  : [{"name":"","digest":"","key":"StartedAt","value":"2020-03-05T07:51:38Z","resourceRef":{}}]
```

This is what I'm seeing in the task run YAML:
```
    - container: step-build
      imageID: >-
        quay.io/buildah/stable@sha256:52a993631e5f13f142c1de0ac19ed2188a1a4190bf4530ecaecb23bece0289c3
      name: build
      terminated:
        containerID: >-
          cri-o://e3c259c8d8290069f646c0178b1c3c0c77d1b4dc04a951017abee83f21113d54
        exitCode: 1
        finishedAt: '2020-03-05T07:52:04Z'
        reason: Error
        startedAt: '2020-03-05T07:51:38Z'
```

Any idea what went wrong here? Thanks in advance!
