### ISSUE TITLE
Error in Tutorial Pipeline Run

### ISSUE THREAD

**Issue by atef23** [openshift/pipelines-tutorial#92]
When I try to run the tutorial on an OCP 4 cluster I can reach the point where I create the pipeline but there are no resources in this YAML:

https://raw.githubusercontent.com/openshift/pipelines-tutorial/master/01_pipeline/04_pipeline.yaml

and I don't get any output when I try:

`tkn resource ls.
`
When I try to run the pipeline using 

```
tkn pipeline start build-and-deploy \
    -w name=shared-workspace,claimName=source-pvc \
    -p deployment-name=vote-api \
    -p git-url=http://github.com/openshift-pipelines/vote-api.git \
    -p IMAGE=image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/vote-api
```

The run fails with the following error:

`invalid input params: didn't need these params but they were provided anyway: [IMAGE]`

Removing the -p IMAGE parameter still results in that error.

Thanks,

Atef

**Comment by khilmanoj** [comment]
Follow the latest doc --> https://docs.openshift.com/container-platform/4.4/pipelines/creating-applications-with-cicd-pipelines.html

**Comment by ppitonak** [comment]
If you installed OpenShift Pipelines 1.0, follow https://github.com/openshift/pipelines-tutorial/tree/release-tech-preview-1 

For Pipelines 1.1 (in preview channel now), follow https://github.com/openshift/pipelines-tutorial/tree/release-tech-preview-2

**Comment by atef23** [comment]
@ppitonak Thanks, I used the link for Openshift Pipelines 1.0. The first time I ran the pipeline I got this error:

`Failed to create build pod "build-and-deploy-run-bkcv7-build-image-qfcc6": pods "build-and-deploy-run-bkcv7-build-image-qfcc6-pod-nzb8d" is forbidden: maximum cpu usage per Pod is 2, but limit is 2500m`

The pipeline run succeeded for me after i increased the cpu limits in `pipelines-tutorial-core-resource-limits` as follows:

```
kind: LimitRange
apiVersion: v1
metadata:
  name: pipelines-tutorial-core-resource-limits
  namespace: pipelines-tutorial
spec:
  limits:
    - type: Container
      max:
        cpu: '3'
        memory: 6Gi
      default:
        cpu: 500m
        memory: 1536Mi
      defaultRequest:
        cpu: 50m
        memory: 256Mi
    - type: Pod
      max:
        cpu: '3'
        memory: 12Gi
```
